const mark = '<span class="corp-mark" aria-hidden="true"><i></i><i></i><i></i></span>';
export const nav = (active = '') => `<div class="corp-progress" aria-hidden="true"><i></i></div><header class="corp-header"><div class="corp-nav-inner"><a class="corp-brand" href="/" aria-label="유성 메인">${mark}<span>U-SUNG</span></a><button class="corp-menu-toggle" aria-expanded="false" aria-controls="corp-navigation" aria-label="사업 메뉴 열기"><span></span><span></span></button><nav class="corp-nav" id="corp-navigation" aria-label="유성 사업 메뉴"><a href="/#company">유성 소개</a><a href="/ai/" ${active === 'ai' ? 'aria-current="page"' : ''}>AI</a><a href="/smart-construction/" ${active === 'construction' ? 'aria-current="page"' : ''}>스마트 건설</a><a href="/physical-ai/" ${active === 'physical' ? 'aria-current="page"' : ''}>Physical AI</a><a class="corp-nav-contact" href="/#contact">프로젝트 문의 <span aria-hidden="true">↗</span></a></nav></div></header>`;
export const footer = `<footer class="corp-footer"><div class="corp-footer-top"><a class="corp-footer-logo" href="/">${mark}<span>U-SUNG</span></a><p>CONSTRUCTION. INTELLIGENCE. BEYOND.</p></div><div class="corp-footer-bottom"><div><strong>유성건설 주식회사</strong><span>부산광역시 동구 중앙대로 373, 3층</span></div><div><a href="tel:+82514699700">051-469-9700</a><span>© ${new Date().getUTCFullYear()} U-SUNG. All rights reserved.</span></div><a class="corp-back-top" href="#main-content">BACK TO TOP ↑</a></div></footer>`;
export const contact = `<section class="corp-contact corp-light" id="contact"><div class="corp-section-top"><span class="corp-eyebrow">LET’S BUILD TOGETHER</span><span class="corp-small">BUSAN, KOREA / OPEN TO WHAT’S NEXT</span></div><h2>WHAT’S<br><span>NEXT?</span></h2><div class="corp-contact-bottom"><p>AI 도입에서 새로운 현장의 구상까지.<br>다음 가능성을 함께 이야기합니다.</p><a class="corp-contact-link" href="mailto:qoengks12@hanmail.net">프로젝트 문의 <b aria-hidden="true">↗</b></a></div><a class="corp-contact-email" href="mailto:qoengks12@hanmail.net">qoengks12@hanmail.net</a></section>`;
const motionButton = `<button class="corp-motion" type="button" aria-pressed="false" aria-label="배경 움직임 일시정지"><span>PAUSE MOTION</span><i aria-hidden="true">Ⅱ</i></button>`;
const roundLink = (href,label) => `<a class="corp-round-link" href="${href}"><span>${label}</span><b aria-hidden="true">↘</b></a>`;
export const home = `<main id="main-content">
<section class="corp-cinema-hero corp-home-hero"><video class="corp-hero-media" muted loop playsinline preload="metadata" poster="/assets/media/turner-hero.jpg" aria-hidden="true"><source src="/assets/media/turner-hero.mp4" type="video/mp4"></video><div class="corp-hero-shade"></div><div class="corp-hero-grid" aria-hidden="true"></div>${motionButton}<div class="corp-hero-content"><p class="corp-eyebrow"><i class="corp-signal" aria-hidden="true"></i> U-SUNG / BEYOND CONSTRUCTION</p><h1 class="corp-display">BUILD<br><span>WHAT’S NEXT.</span></h1><div class="corp-hero-bottom"><p>현장의 경험이,<br>새로운 지능을 만납니다.</p>${roundLink('#business','EXPLORE U-SUNG')}</div></div><div class="corp-hero-foot"><span>AI & AX</span><i></i><span>SMART CONSTRUCTION</span><i></i><span>PHYSICAL AI</span><a href="#business">SCROLL TO DISCOVER ↓</a></div></section>
<section class="corp-intro corp-light" id="company"><span class="corp-eyebrow">01 / THE NEXT U-SUNG</span><div class="corp-intro-main"><h2>현실을 짓는 경험.<br><em>가능성을 여는 지능.</em></h2><div class="corp-intro-bottom"><p>2007년부터 쌓아온 건설의 실행력.<br>이제 AI, 스마트 건설, Physical AI로<br>유성의 다음을 만들어갑니다.</p><div class="corp-company-facts"><span><b>2007</b>ESTABLISHED</span><span><b>BUSAN</b>BASED IN KOREA</span></div></div></div></section>
<section class="corp-business" id="business"><div class="corp-section-top"><span class="corp-eyebrow">02 / OUR BUSINESSES</span><span class="corp-small">ONE COMPANY. EXPANDING POSSIBILITIES.</span></div><div class="corp-business-heading"><h2>THREE FIELDS.<br><span>ONE FORWARD.</span></h2><p>디지털의 판단부터 실제 현장의 실행까지.<br>유성의 사업을 만나보세요.</p></div><div class="corp-business-grid">
<a class="corp-business-card corp-ai-card" href="/ai/"><canvas class="corp-neural" data-neural="card" aria-hidden="true"></canvas><div class="corp-card-shade"></div><div class="corp-card-top"><span>01 / INTELLIGENCE</span><b aria-hidden="true">↗</b></div><div class="corp-card-bottom"><span>AI & AX</span><h3>Intelligence.</h3><p>신뢰할 수 있는 판단.<br>업무를 바꾸는 실행.</p><span class="corp-card-link">AI 사업 살펴보기 <i aria-hidden="true">→</i></span></div></a>
<a class="corp-business-card" href="/smart-construction/"><img src="/assets/media/suffolk-project.jpg" alt="유리와 금속 구조가 어우러진 현대 건축" loading="lazy"><div class="corp-card-shade"></div><div class="corp-card-top"><span>02 / SMART CONSTRUCTION</span><b aria-hidden="true">↗</b></div><div class="corp-card-bottom"><span>스마트 건설</span><h3>Build beyond.</h3><p>현장을 이해하는 경험.<br>기술로 넓어지는 건설.</p><span class="corp-card-link">스마트 건설 살펴보기 <i aria-hidden="true">→</i></span></div></a>
<a class="corp-business-card" href="/physical-ai/"><img src="/assets/media/built-rpd.jpg" alt="실제 현장에서 작업하는 자율 건설 장비" loading="lazy"><div class="corp-card-shade"></div><div class="corp-card-top"><span>03 / PHYSICAL AI</span><b aria-hidden="true">↗</b></div><div class="corp-card-bottom"><span>Physical AI</span><h3>Into the real.</h3><p>지능의 가능성이<br>현장의 움직임으로.</p><span class="corp-card-link">Physical AI 살펴보기 <i aria-hidden="true">→</i></span></div></a>
</div></section>
<section class="corp-feature"><img src="/assets/media/built-sundown.jpg" alt="저녁의 건설 현장과 자율 장비" loading="lazy"><div class="corp-feature-shade"></div><div class="corp-feature-content"><p class="corp-eyebrow">U-SUNG × OmarAGI</p><h2>FROM<br>INTELLIGENCE<br><span>TO IMPACT.</span></h2><div class="corp-feature-bottom"><p>AI의 판단을 검증하고,<br>업무와 현장의 실행으로 연결합니다.</p><a class="corp-line-link" href="/ai/">AI 신뢰·실행 인프라 <b aria-hidden="true">↗</b></a></div></div></section>${contact}</main>`;
export const ai = `<main id="main-content">
<section class="corp-cinema-hero corp-ai-hero"><canvas class="corp-neural" data-neural="hero" aria-hidden="true"></canvas><div class="corp-ai-vignette"></div><div class="corp-hero-grid" aria-hidden="true"></div>${motionButton}<div class="corp-hero-content"><p class="corp-eyebrow"><i class="corp-signal" aria-hidden="true"></i> U-SUNG AI / IN PARTNERSHIP WITH OmarAGI</p><h1 class="corp-display">INTELLIGENCE.<br><span>IN ACTION.</span></h1><div class="corp-hero-bottom"><p>믿을 수 있는 판단.<br>끝까지 이어지는 실행.</p>${roundLink('#capabilities','EXPLORE AI')}</div></div><div class="corp-hero-foot"><span>MODEL-AGNOSTIC</span><i></i><span>VERIFY · ROUTE · EXECUTE</span><a href="#capabilities">SCROLL TO DISCOVER ↓</a></div></section>
<section class="corp-intro corp-light"><span class="corp-eyebrow">01 / RELIABILITY INFRASTRUCTURE</span><div class="corp-intro-main"><h2>답을 생성하는 AI에서.<br><em>결과를 책임지는 실행으로.</em></h2><div class="corp-intro-bottom"><p>모델의 답이 실제 업무에 쓰이기까지.<br>근거, 검증, 실행 조건을 연결합니다.</p><p>유성의 적용 역량과 OmarAGI의<br>AI 신뢰·실행 인프라가 함께합니다.</p></div></div></section>
<section class="corp-capabilities corp-light" id="capabilities"><div class="corp-cap-intro"><p class="corp-eyebrow">02 / CORE CAPABILITIES</p><h2>TRUST.<br>CONTROL.<br><span>EXECUTE.</span></h2><p>AI가 실제 업무에서 작동하기 위한<br>세 가지 핵심 역량.</p></div><div class="corp-cap-list">
<details open><summary><span>01</span><h3>VERIFY</h3><b aria-hidden="true">+</b></summary><div><h4>답변과 결과 검증</h4><p>출처와 근거를 연결하고, 데이터의 일관성을 확인합니다. RAG와 AI 결과가 업무에 채택되기 전 검증 과정을 설계합니다.</p><small>GROUNDING / PROVENANCE / EVALUATION</small></div></details>
<details><summary><span>02</span><h3>CONTROL</h3><b aria-hidden="true">+</b></summary><div><h4>에이전트와 워크플로 제어</h4><p>업무에 맞는 모델과 경로를 선택하고, 실행 순서와 승인 조건을 관리합니다. 판단에서 실행까지 흐름을 연결합니다.</p><small>ROUTING / AGENT CONTROL / ADOPTION GATE</small></div></details>
<details><summary><span>03</span><h3>OBSERVE</h3><b aria-hidden="true">+</b></summary><div><h4>운영과 거버넌스</h4><p>응답과 실행 기록을 남기고 이상 징후와 실패를 추적합니다. 관찰, 감사, 평가가 이어지는 운영 환경을 설계합니다.</p><small>OBSERVABILITY / AUDIT / GOVERNANCE</small></div></details>
</div></section>
<section class="corp-workflow" id="approach"><div class="corp-section-top"><p class="corp-eyebrow">03 / FROM INPUT TO EXECUTION</p><span class="corp-small">U-SUNG × OmarAGI</span></div><h2>CONNECTED<br><span>BY TRUST.</span></h2><div class="corp-flow-grid"><article><span>01 / UNDERSTAND</span><h3>현장을 읽습니다.</h3><p>업무, 데이터, 현장 요구를 정의하고 AI가 해결할 과제를 구체화합니다.</p></article><article><span>02 / VERIFY</span><h3>판단을 확인합니다.</h3><p>모델의 결과와 근거를 검증하고, 실행에 필요한 조건을 확인합니다.</p></article><article><span>03 / EXECUTE</span><h3>실행으로 연결합니다.</h3><p>검증된 결과를 실제 워크플로에 연결하고 실행 기록으로 다시 평가합니다.</p></article></div></section>${contact}</main>`;
export const physical = `<main id="main-content">
<section class="corp-cinema-hero corp-physical-hero"><img class="corp-hero-media" src="/assets/media/built-sundown.jpg" alt="자율 건설 장비가 작업하는 실제 현장"><div class="corp-hero-shade"></div><div class="corp-hero-grid" aria-hidden="true"></div><div class="corp-hero-content"><p class="corp-eyebrow"><i class="corp-signal" aria-hidden="true"></i> U-SUNG / PHYSICAL AI</p><h1 class="corp-display">INTELLIGENCE.<br><span>IN THE FIELD.</span></h1><div class="corp-hero-bottom"><p>지능이 현실을 읽고,<br>현실의 움직임으로 이어집니다.</p>${roundLink('#capabilities','EXPLORE THE FIELD')}</div></div><div class="corp-hero-foot"><span>PERCEPTION</span><i></i><span>VERIFICATION</span><i></i><span>REAL-WORLD ACTION</span><a href="#capabilities">SCROLL TO DISCOVER ↓</a></div></section>
<section class="corp-intro corp-light"><span class="corp-eyebrow">01 / INTELLIGENCE MEETS THE FIELD</span><div class="corp-intro-main"><h2>현장을 아는 경험에.<br><em>스스로 판단하는 기술을.</em></h2><div class="corp-intro-bottom"><p>유성의 건설 경험과 AI 기술을 연결합니다.<br>센서와 데이터, 검증과 제어가 만나는<br>Physical AI의 적용 방향을 구체화합니다.</p><a class="corp-line-link" href="/smart-construction/">스마트 건설과의 연결 <b aria-hidden="true">↗</b></a></div></div></section>
<section class="corp-field" id="capabilities"><div class="corp-section-top"><p class="corp-eyebrow">02 / SEE. DECIDE. ACT.</p><span class="corp-small">FROM DIGITAL TO PHYSICAL</span></div><div class="corp-field-display"><div class="corp-field-images"><img class="is-active" data-field-image="0" src="/assets/media/suffolk-robotics.jpg" alt="현장의 로봇과 센서 기술" loading="lazy"><img data-field-image="1" src="/assets/media/built-rpd.jpg" alt="현장 데이터를 활용하는 자율 장비" loading="lazy"><img data-field-image="2" src="/assets/media/built-trenching.jpg" alt="실제 작업을 수행하는 자율 굴착 장비" loading="lazy"><span class="corp-field-image-label" aria-hidden="true">TECHNOLOGY IN CONTEXT</span></div><div class="corp-field-controls" role="tablist" aria-label="Physical AI 적용 단계">
<button class="is-active" type="button" role="tab" aria-selected="true" aria-controls="field-panel-0" id="field-tab-0" data-field-tab="0"><span>01 / PERCEPTION</span><b>SEE.</b></button><button type="button" role="tab" aria-selected="false" aria-controls="field-panel-1" id="field-tab-1" data-field-tab="1" tabindex="-1"><span>02 / VERIFICATION</span><b>DECIDE.</b></button><button type="button" role="tab" aria-selected="false" aria-controls="field-panel-2" id="field-tab-2" data-field-tab="2" tabindex="-1"><span>03 / EXECUTION</span><b>ACT.</b></button>
<div role="tabpanel" id="field-panel-0" aria-labelledby="field-tab-0"><h3>현장의 변화를 읽습니다.</h3><p>센서, 비전, 현장 데이터로 작업 환경을 인식합니다. 데이터의 일관성과 이상 징후를 함께 살핍니다.</p></div><div role="tabpanel" id="field-panel-1" aria-labelledby="field-tab-1" hidden><h3>행동에 앞서 판단을 검증합니다.</h3><p>판단 근거, 실행 조건, 승인 절차를 연결합니다. 행동에 앞서 결과를 확인하는 신뢰 레이어를 설계합니다.</p></div><div role="tabpanel" id="field-panel-2" aria-labelledby="field-tab-2" hidden><h3>검증을 실제 실행으로 연결합니다.</h3><p>에이전트와 현장 시스템을 연결하고 결과를 다시 확인합니다. PoC와 실증으로 적용 범위를 구체화합니다.</p></div>
</div></div></section><section class="corp-field-bridge"><img src="/assets/media/built-sunrise.jpg" alt="새벽의 스마트 건설 현장" loading="lazy"><div class="corp-feature-shade"></div><div class="corp-feature-content"><p class="corp-eyebrow">THE FIRST CONNECTION / SMART CONSTRUCTION</p><h2>THE NEXT<br><span>REALITY.</span></h2><div class="corp-feature-bottom"><p>새로운 현장의 가능성.<br>유성 스마트 건설에서 시작합니다.</p>${roundLink('/smart-construction/','SMART CONSTRUCTION')}</div></div></section>${contact}</main>`;
