import { brandLogo } from './brand.mjs';
export const nav = (active = '') => `<div class="corp-progress" aria-hidden="true"><i></i></div><header class="corp-header"><div class="corp-nav-inner"><a class="corp-brand" href="/" aria-label="유성 메인">${brandLogo('header')}</a><nav class="corp-nav" id="corp-navigation" aria-label="유성 사업 메뉴"><a href="/" ${active === '' ? 'aria-current="page"' : ''}>메인</a><a href="/ai/" ${active === 'ai' ? 'aria-current="page"' : ''}>AI</a><a href="/smart-construction/" ${active === 'construction' ? 'aria-current="page"' : ''}>스마트 건설</a><a href="/physical-ai/" ${active === 'physical' ? 'aria-current="page"' : ''}>Physical AI</a></nav><div class="corp-header-actions"><a class="corp-header-contact" href="/#contact" aria-label="프로젝트 문의"><span class="corp-contact-label">프로젝트 문의</span></a><usung-language></usung-language></div></div></header>`;
export const footer = `<footer class="corp-footer"><div class="corp-footer-top"><a class="corp-footer-logo" href="/" aria-label="유성 메인">${brandLogo('footer')}</a><p>CONSTRUCTION. INTELLIGENCE. BEYOND.</p></div><div class="corp-footer-bottom"><div><strong>유성건설 주식회사</strong><span>부산광역시 동구 중앙대로 373, 3층</span></div><div><a href="tel:+82514699700">051-469-9700</a><span>© ${new Date().getUTCFullYear()} U-SUNG. All rights reserved.</span></div></div></footer>`;
export const contact = `<section class="corp-contact corp-light" id="contact"><div class="corp-section-top"><span class="corp-eyebrow">LET’S BUILD TOGETHER</span><span class="corp-small">BUSAN, KOREA / OPEN TO WHAT’S NEXT</span></div><h2>WHAT’S<br><span>NEXT?</span></h2><div class="corp-contact-bottom"><p>AI 도입에서 새로운 현장의 구상까지.<br>다음 가능성을 함께 이야기합니다.</p><a class="corp-contact-link" href="mailto:qoengks12@hanmail.net">프로젝트 문의</a></div><a class="corp-contact-email" href="mailto:qoengks12@hanmail.net">qoengks12@hanmail.net</a></section>`;
const motionButton = `<button class="corp-motion" type="button" aria-pressed="false" aria-label="배경 움직임 일시정지"><span>PAUSE MOTION</span><i aria-hidden="true">Ⅱ</i></button>`;
export const home = `<main id="main-content">
<section class="corp-main-landing corp-light" aria-label="유성 메인">
<div class="corp-main-heading"><div><p class="corp-eyebrow">U-SUNG CORPORATION / EST. 2007</p><h1>BUILD<br><span>WHAT’S NEXT.</span></h1></div><div class="corp-main-intro"><p>현장을 짓는 경험.<br>미래를 여는 지능.</p></div></div>
<div class="corp-main-business" id="business"><div class="corp-main-business-label"><span>EXPLORE OUR BUSINESSES</span><span>AI · SMART CONSTRUCTION · PHYSICAL AI</span></div><div class="corp-business-grid">
<a class="corp-business-card corp-ai-card corp-source-ai-card" href="/ai/"><img src="/assets/generated/ai-glass-extended-v1.png" alt="투명한 입체 구조의 AI 시각물" loading="lazy" width="1536" height="1024"><div class="corp-card-shade"></div><div class="corp-card-top"><span>01 / INTELLIGENCE</span></div><div class="corp-card-bottom"><span>AI & AX</span><h3>Intelligence.</h3><p>신뢰할 수 있는 판단.<br>업무를 바꾸는 실행.</p></div></a>
<a class="corp-business-card" href="/smart-construction/"><img src="/assets/media/suffolk-project.jpg" alt="유리와 금속 구조가 어우러진 현대 건축" loading="lazy"><div class="corp-card-shade"></div><div class="corp-card-top"><span>02 / SMART CONSTRUCTION</span></div><div class="corp-card-bottom"><span>스마트 건설</span><h3>Build beyond.</h3><p>현장을 이해하는 경험.<br>기술로 넓어지는 건설.</p></div></a>
<a class="corp-business-card" href="/physical-ai/"><video muted loop playsinline preload="none" poster="/assets/references/dexterity-hero-poster.jpg" aria-hidden="true"><source src="/assets/references/dexterity-hero.mp4" type="video/mp4"></video><div class="corp-card-shade"></div><div class="corp-card-top"><span>03 / PHYSICAL AI</span></div><div class="corp-card-bottom"><span>Physical AI</span><h3>Into the real.</h3><p>지능의 가능성이<br>현장의 움직임으로.</p></div></a>
</div></div>
</section>
<section class="corp-intro corp-light" id="company"><span class="corp-eyebrow">01 / THE NEXT U-SUNG</span><div class="corp-intro-main"><h2>현실을 짓는 경험.<br><em>가능성을 여는 지능.</em></h2><div class="corp-intro-bottom"><p>2007년부터 쌓아온 건설의 실행력.<br>이제 AI, 스마트 건설, Physical AI로<br>유성의 다음을 만들어갑니다.</p><div class="corp-company-facts"><span><b>2007</b>ESTABLISHED</span><span><b>BUSAN</b>BASED IN KOREA</span></div></div></div></section>

<section class="corp-feature"><img src="/assets/media/built-sundown.jpg" alt="저녁의 건설 현장과 자율 장비" loading="lazy"><div class="corp-feature-shade"></div><div class="corp-feature-content"><p class="corp-eyebrow">U-SUNG × OmarAGI</p><h2>FROM<br>INTELLIGENCE<br><span>TO IMPACT.</span></h2><div class="corp-feature-bottom"><p>AI의 판단을 검증하고,<br>업무와 현장의 실행으로 연결합니다.</p></div></div></section>${contact}</main>`;
const sourceCredit = (url, name, label = 'VISUAL REFERENCE') => `<a class="ref-credit" href="${url}" target="_blank" rel="noopener noreferrer">${label} / ${name} ↗</a>`;
const sourceVideo = (name, cls = '', preload = 'none') => `<video class="${cls}" muted loop playsinline preload="${preload}" poster="/assets/references/${name}-poster.jpg" aria-hidden="true"><source src="/assets/references/${name}.mp4" type="video/mp4"></video>`;
export const ai = `<main id="main-content">
<section class="ref-ai-hero">
 <div class="ref-ai-art"><img src="/assets/generated/ai-glass-extended-v1.png" alt="투명한 입체 구조로 표현한 AI 인프라" fetchpriority="high" width="1536" height="1024"></div>
 <div class="ref-ai-hero-copy"><p class="corp-eyebrow">U-SUNG AI / POWERED WITH OmarAGI</p><h1>AI.<br>BUILT FOR<br><span>REAL WORK.</span></h1><p class="ref-hero-description">AI의 판단에 근거를.<br>업무의 실행에 신뢰를.</p></div>
 <div class="ref-hero-strip"><span>MODEL-AGNOSTIC</span><span>VERIFY / CONTROL / OBSERVE</span>${sourceCredit('https://contextual.ai/','CONTEXTUAL AI')}</div>
</section>
<section class="ref-statement corp-light"><div class="corp-section-top"><span class="corp-eyebrow">01 / RELIABILITY, BY DESIGN</span><span class="corp-small">U-SUNG × OmarAGI</span></div><div class="ref-statement-grid"><h2>지능이 업무가 되는 순간.<br><span>그 사이에 신뢰를 설계합니다.</span></h2><p>어떤 모델을 쓰든, 결과가 실제 업무에 연결되기까지.<br>유성의 현장·업무 적용 역량과 OmarAGI의 AI 신뢰·실행 인프라가 함께합니다.</p></div><div class="ref-principles"><span>근거에 연결된 판단</span><span>조건에 따라 제어되는 실행</span><span>기록으로 확인하는 운영</span></div></section>
<section class="ref-platform corp-light" id="platform"><div class="corp-section-top"><span class="corp-eyebrow">02 / THE RELIABILITY LAYER</span><span class="corp-small">ONE INFRASTRUCTURE. ANY MODEL.</span></div><div class="ref-platform-heading"><h2>TRUST IS<br><span>BUILT IN.</span></h2><p>모델과 데이터, 실제 업무 사이.<br>검증·제어·관찰을 하나의 흐름으로 연결합니다.</p></div>
<div class="ref-platform-layout" data-ref-tabs>
 <div class="ref-platform-controls" role="tablist" aria-label="AI 인프라 핵심 역량">
 <button role="tab" id="ai-tab-0" aria-controls="ai-panel-0" aria-selected="true" data-ref-tab="0"><span>01 / VERIFY</span><strong>판단을 검증합니다.</strong></button>
 <button role="tab" id="ai-tab-1" aria-controls="ai-panel-1" aria-selected="false" tabindex="-1" data-ref-tab="1"><span>02 / CONTROL</span><strong>실행을 제어합니다.</strong></button>
 <button role="tab" id="ai-tab-2" aria-controls="ai-panel-2" aria-selected="false" tabindex="-1" data-ref-tab="2"><span>03 / OBSERVE</span><strong>운영을 관찰합니다.</strong></button>
 </div><div class="ref-platform-visual">
 <div role="tabpanel" id="ai-panel-0" aria-labelledby="ai-tab-0" data-ref-panel="0"><img src="/assets/references/contextual-intelligence.svg" alt="모델과 AI 애플리케이션 계층을 표현한 레퍼런스 도식" loading="lazy"><div class="ref-panel-description"><h3>근거가 확인된 결과.</h3><p>출처와 근거를 연결하고 데이터의 일관성을 확인합니다. RAG와 에이전트의 결과가 업무에 채택되기 전 검증 조건을 설계합니다.</p><span>GROUNDING / PROVENANCE / OUTPUT VALIDATION</span></div></div>
 <div role="tabpanel" id="ai-panel-1" aria-labelledby="ai-tab-1" data-ref-panel="1" hidden><img src="/assets/references/contextual-context.svg" alt="AI 모델과 데이터 사이의 컨텍스트 계층을 표현한 레퍼런스 도식" loading="lazy"><div class="ref-panel-description"><h3>판단에서 실행까지.</h3><p>업무에 맞는 모델과 경로를 선택하고 에이전트의 실행 순서·승인 조건을 연결합니다. 결과를 채택하는 단계까지 워크플로를 제어합니다.</p><span>ROUTING / AGENT CONTROL / ADOPTION GATE</span></div></div>
 <div role="tabpanel" id="ai-panel-2" aria-labelledby="ai-tab-2" data-ref-panel="2" hidden><img src="/assets/references/contextual-data.svg" alt="지식과 데이터를 연결하는 기반 계층의 레퍼런스 도식" loading="lazy"><div class="ref-panel-description"><h3>다시 확인할 수 있는 실행.</h3><p>응답과 실행 기록을 연결하고 이상 징후와 실패를 추적합니다. 평가, 관찰, 감사가 이어지는 운영 구조를 설계합니다.</p><span>OBSERVABILITY / EVALUATION / AUDIT LOGGING</span></div></div>
 ${sourceCredit('https://contextual.ai/','CONTEXTUAL AI','DIAGRAM REFERENCE')}</div>
</div></section>
<section class="ref-applications" id="applications"><div class="corp-section-top"><span class="corp-eyebrow">03 / INTELLIGENCE, APPLIED</span><span class="corp-small">FROM DOCUMENTS TO THE FIELD</span></div><h2>REAL WORK.<br><span>REAL CONTEXT.</span></h2><div class="ref-usecases"><article><span class="ref-usecase-number">01</span><h3>문서와 지식</h3><p>계약서, 기술 문서, 현장 기록.<br>분산된 정보를 출처에 연결하고<br>업무에 쓰이는 답변을 검증합니다.</p><span>DOCUMENTS / RAG / SOURCE GROUNDING</span></article><article><span class="ref-usecase-number">02</span><h3>업무와 에이전트</h3><p>다단계 업무와 AI 에이전트.<br>실행 순서와 승인 조건을 연결하고<br>결과를 다시 확인할 수 있게 합니다.</p><span>AGENTS / ROUTING / EXECUTION</span></article><article><span class="ref-usecase-number">03</span><h3>현장과 데이터</h3><p>센서, 공공 데이터, 운영 로그.<br>데이터의 정합성과 이상 징후를 살피고<br>현장의 판단으로 연결합니다.</p><span>DATA CONSISTENCY / ANOMALY DETECTION</span></article></div></section>
<section class="ref-ai-bridge corp-light"><div><p class="corp-eyebrow">DIGITAL INTELLIGENCE. PHYSICAL IMPACT.</p><h2>지능의 다음은,<br><span>현장의 실행입니다.</span></h2><p>AI의 신뢰·실행 인프라를 스마트 건설과 Physical AI로 연결합니다.</p></div><figure><img src="/assets/generated/ai-glass-extended-v1.png" alt="유성 AI 페이지에 사용한 입체 시각물" loading="lazy" width="1536" height="1024">${sourceCredit('https://contextual.ai/','CONTEXTUAL AI')}</figure></section>
${contact}</main>`;
export const physical = `<main id="main-content">
<section class="ref-physical-hero">
 ${sourceVideo('dexterity-hero','ref-full-media','metadata')}<div class="ref-physical-shade"></div>${motionButton}
 <div class="ref-physical-hero-copy"><p class="corp-eyebrow">U-SUNG / PHYSICAL AI</p><h1>INTELLIGENCE.<br>IN THE<br><span>REAL WORLD.</span></h1><div class="ref-physical-hero-bottom"><p>현장을 읽고, 판단을 확인하고,<br>실제 움직임으로 연결합니다.</p></div></div>
 <div class="ref-hero-strip"><span>PERCEPTION / VERIFICATION / ACTION</span>${sourceCredit('https://dexterity.ai/','DEXTERITY','REFERENCE FOOTAGE')}</div>
</section>
<section class="ref-statement corp-light"><div class="corp-section-top"><span class="corp-eyebrow">01 / FROM DIGITAL TO PHYSICAL</span><span class="corp-small">INTELLIGENCE MEETS THE FIELD</span></div><div class="ref-statement-grid"><h2>현장을 아는 경험에.<br><span>스스로 판단하는 기술을.</span></h2><p>유성의 건설 경험과 AI 기술을 연결합니다.<br>센서·비전·현장 시스템에서 얻은 데이터를 바탕으로 Physical AI의 적용 방향을 구체화합니다.</p></div><div class="ref-principles"><span>현장을 읽는 인식</span><span>행동에 앞서는 검증</span><span>기록으로 연결되는 실행</span></div></section>
<section class="ref-motion-section" id="field"><div class="corp-section-top"><span class="corp-eyebrow">02 / SEE. DECIDE. ACT.</span><span class="corp-small">THE PATH TO REAL-WORLD ACTION</span></div><div class="ref-motion-heading"><h2>THE FIELD.<br><span>CONNECTED.</span></h2><p>현실의 변화가 데이터가 되고,<br>검증된 판단이 실행으로 이어집니다.</p></div><div class="ref-motion-grid">
 <article>${sourceVideo('dexterity-perception')}<div class="ref-motion-shade"></div><div class="ref-motion-copy"><span>01 / PERCEPTION</span><h3>SEE.</h3><p>센서와 비전으로<br>작업 환경을 읽습니다.</p></div></article>
 <article>${sourceVideo('dexterity-coordination')}<div class="ref-motion-shade"></div><div class="ref-motion-copy"><span>02 / VERIFICATION</span><h3>DECIDE.</h3><p>판단 근거와 실행 조건을<br>행동에 앞서 확인합니다.</p></div></article>
 <article>${sourceVideo('dexterity-precision')}<div class="ref-motion-shade"></div><div class="ref-motion-copy"><span>03 / EXECUTION</span><h3>ACT.</h3><p>현장 시스템에 연결하고<br>작업 결과를 다시 살핍니다.</p></div></article>
 </div><div class="ref-motion-foot"><span>현장 인식부터 결과 확인까지, 하나의 실행 흐름.</span>${sourceCredit('https://dexterity.ai/','DEXTERITY','REFERENCE FOOTAGE')}</div></section>
<section class="ref-world-model corp-light"><div class="corp-section-top"><span class="corp-eyebrow">03 / A RELIABILITY LAYER FOR THE FIELD</span><span class="corp-small">ANY MACHINE. ONE CONNECTED WORKFLOW.</span></div><div class="ref-world-layout"><figure><img src="/assets/references/field-world-model.webp" alt="로봇의 현장 인식과 공간 데이터를 시각화한 Field AI 레퍼런스" loading="lazy" width="1600" height="900">${sourceCredit('https://www.fieldai.com/','FIELD AI')}</figure><div><h2>현실은 변합니다.<br><span>판단은 검증합니다.</span></h2><p>현장의 불확실성을 데이터로 읽고, AI의 판단에 실행 조건을 연결합니다. 특정 모델이나 장비에 종속되지 않는 신뢰·실행 계층을 적용합니다.</p></div></div></section>
<section class="ref-field-cinema">${sourceVideo('field-robots','ref-full-media')}<div class="ref-physical-shade"></div><div class="ref-field-cinema-copy"><p class="corp-eyebrow">THE FIRST CONNECTION / SMART CONSTRUCTION</p><h2>BUILT FOR<br><span>THE FIELD.</span></h2><p>건설의 경험에서 출발하는 Physical AI.<br>실제 현장의 과제를 PoC와 실증으로 구체화합니다.</p></div>${sourceCredit('https://www.fieldai.com/','FIELD AI','REFERENCE FOOTAGE')}</section>
${contact}</main>`;
